'use strict';
// Writes the constant tables of the lpic format (lpic.js) for the shaders, so they use exactly the reference's numbers:
//   node lpic-hlsl.js  -> measure/unity/Assets/ParamroomLocalImage/Shaders/ParamroomLocalImageTables.cginc
const fs = require('fs');
const path = require('path');
const L = require('./lpic');
const D = require('../lib/dct');

const tables = [L.TBL.dc[0], L.TBL.dc[1], L.TBL.ac[0], L.TBL.ac[1]]; // 0 DC Y, 1 DC C, 2 AC Y, 3 AC C
const arr = (a, fmt = String) => '{ ' + Array.from(a, fmt).join(', ') + ' }';
const f32 = v => { const s = Math.fround(v).toPrecision(9); return s.includes('e') || s.includes('.') ? s : s + '.0'; };
const cos = new Float32Array(64);
for (let x = 0; x < 8; x++) for (let u = 0; u < 8; u++) cos[x * 8 + u] = Math.cos((2 * x + 1) * u * Math.PI / 16) * (u === 0 ? Math.SQRT1_2 : 1) * 0.5;

const out = `// GENERATED by sim/local/lpic-hlsl.js from sim/local/lpic.js - do not edit.
// Tables of the Paramroom local image format v1 (JPEG standard Huffman tables, zigzag, base quantisation, IDCT cosines).
#ifndef PARAMROOM_LOCAL_IMAGE_TABLES
#define PARAMROOM_LOCAL_IMAGE_TABLES
// Huffman tables: 0 = DC luma, 1 = DC chroma, 2 = AC luma, 3 = AC chroma. Index 1..16 = code length.
static const int HUFF_MAXCODE[4][17] = { ${tables.map(t => arr(t.maxcode)).join(', ')} };
static const int HUFF_MINCODE[4][17] = { ${tables.map(t => arr(t.mincode)).join(', ')} };
static const int HUFF_VALPTR[4][17] = { ${tables.map(t => arr(t.valptr)).join(', ')} };
static const uint HUFF_VALS[4][162] = { ${tables.map(t => arr(Array.from({ length: 162 }, (_, i) => t.vals[i] ?? 0))).join(', ')} };
// ZIGZAG[k] = raster index (v * 8 + u) of the k-th coefficient
static const uint ZIGZAG[64] = ${arr(D.ZIGZAG)};
// JPEG base quantisation tables (raster), scaled by the quality in the shader (libjpeg integer formula)
static const uint QBASE[2][64] = { ${arr(D.QY)}, ${arr(D.QC)} };
// COS8[x * 8 + u] = C(u) / 2 * cos((2x + 1) u pi / 16), float32 as in the reference
static const float COS8[64] = ${arr(cos, f32)};
#endif
`;
const dst = path.join(__dirname, '..', '..', 'measure', 'unity', 'Assets', 'ParamroomLocalImage', 'Shaders', 'ParamroomLocalImageTables.cginc');
fs.mkdirSync(path.dirname(dst), { recursive: true });
fs.writeFileSync(dst, out);
console.log('wrote', path.relative(process.cwd(), dst));
